"""Cross-algorithm input-delay (nk) convention tests.

Every algorithm must interpret ``nk`` as the delay of the first B coefficient
(``nk=1`` -> ``u[k-1]``), matching ARX/FIR and the MATLAB convention. These
tests identify models from data generated by a known plant with delay ``nk``
and require the identified state-space model to reproduce a held-out
validation response, which fails if any algorithm applies an off-by-one delay.
"""

import numpy as np
import pytest
from scipy import signal

from sippy.identification.factory import create_algorithm

DEN = np.array([1.0, -1.2, 0.35])  # poles at 0.5 and 0.7
B_COEFFS = np.array([0.5, 0.3])


def _gbn(n, rng):
    u = np.zeros(n)
    val = rng.choice([-1.0, 1.0])
    for k in range(n):
        if rng.uniform() < 0.05:
            val = -val
        u[k] = val
    return u


def _make_data(nk_true, n=600, noise=0.01, seed=0):
    rng = np.random.default_rng(seed)
    num = np.zeros(nk_true + len(B_COEFFS))
    num[nk_true:] = B_COEFFS
    u = _gbn(n, rng)
    y = signal.lfilter(num, DEN, u)
    y += noise * y.std() * rng.normal(size=n)
    u_val = _gbn(n, np.random.default_rng(seed + 999))
    y_val = signal.lfilter(num, DEN, u_val)
    return u[None, :], y[None, :], u_val[None, :], y_val[None, :]


def _simulate(model, u):
    A, B, C, D = model.A, model.B, model.C, model.D
    x = np.zeros(A.shape[0])
    y = np.zeros((C.shape[0], u.shape[1]))
    for k in range(u.shape[1]):
        y[:, k] = C @ x + D @ u[:, k]
        x = A @ x + B @ u[:, k]
    return y


def _fit_percent(y_true, y_hat):
    num = np.linalg.norm(y_true - y_hat)
    den = np.linalg.norm(y_true - y_true.mean(axis=1, keepdims=True))
    return 100.0 * (1.0 - num / den)


DELAY_METHODS = [
    ("ARX", {"na": 2, "nb": 2}),
    ("FIR", {"nb": 30}),
    ("ARMAX", {"na": 2, "nb": 2, "nc": 1, "mode": "ILLS"}),
    ("OE", {"nb": 2, "nf": 2}),
    ("BJ", {"nb": 2, "nc": 1, "nd": 1, "nf": 2}),
    ("ARARX", {"na": 2, "nb": 2, "nd": 1}),
    ("ARARMAX", {"na": 2, "nb": 2, "nc": 1, "nd": 1}),
    ("GEN", {"na": 0, "nb": 2, "nc": 1, "nd": 1, "nf": 2}),
]


@pytest.mark.parametrize("nk_true", [1, 2])
@pytest.mark.parametrize("method,orders", DELAY_METHODS, ids=lambda v: str(v))
def test_nk_means_delay_of_first_b_coefficient(method, orders, nk_true):
    u, y, u_val, y_val = _make_data(nk_true)
    model = create_algorithm(method).identify(
        y=y, u=u, nk=nk_true, max_iterations=100, **orders
    )
    y_hat = _simulate(model, u_val)
    fit = _fit_percent(y_val[:, 50:], y_hat[:, 50:])
    assert np.isfinite(fit), f"{method} produced a non-finite simulation"
    assert fit > 85.0, f"{method} nk={nk_true} held-out fit {fit:.1f}% (delay bias?)"


def test_armax_explicit_theta_keeps_extra_delay_convention():
    """theta is the master-branch extra delay: theta=0 places b1 at u[k-1]."""
    u, y, u_val, y_val = _make_data(nk_true=2)
    model = create_algorithm("ARMAX").identify(
        y=y, u=u, na=2, nb=2, nc=1, theta=1, mode="ILLS", max_iterations=100
    )
    y_hat = _simulate(model, u_val)
    fit = _fit_percent(y_val[:, 50:], y_hat[:, 50:])
    assert fit > 85.0, f"ARMAX theta=1 held-out fit {fit:.1f}%"


def test_nk_zero_warns_and_degrades_to_one():
    u, y, _, _ = _make_data(nk_true=1)
    with pytest.warns(UserWarning, match="direct feedthrough"):
        model = create_algorithm("OE").identify(
            y=y, u=u, nb=2, nf=2, nk=0, max_iterations=50
        )
    assert np.all(np.isfinite(model.A))
